# Generated by Django 6.0 on 2025-12-06 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('suburb', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('price_per_week', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_type', models.CharField(choices=[('private', 'Private Room'), ('shared', 'Shared Room'), ('studio', 'Studio Apartment'), ('whole', 'Whole Property')], default='private', max_length=20)),
                ('description', models.TextField()),
                ('availability_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='core.room')),
            ],
        ),
    ]
