# Generated by Django 6.0 on 2025-12-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='inspection_time',
            field=models.CharField(blank=True, help_text='e.g. Saturday 10:00 AM - 11:00 AM', max_length=100, null=True),
        ),
    ]
